src/main/java/entities/Client.java
package entities;

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlRootElement;

@Entity
@XmlRootElement
public class Client extends StoreUser{
    private ShoppingCar car;
    public Client(){
        super();
        car = new ShoppingCar();
    }
    public Client(int SSN, String email, String password){
        super(SSN,email,password);
        car = new ShoppingCar();
    }
    
    public ShoppingCar getCar() {
        return car;
    }

    public void setCar(ShoppingCar car) {
        this.car = car;
    }

    
    @Override
    public String toString() {
        return "{\"ClientId\":\"" + super.getUserId() + "\", \"Name\":\"" + super.getName()+ "\", \"Email\":\"" + super.getEmail() + "\","
                + " \"Address\":\"" + super.getAddress() + "\", \"SSN\":\"" + super.getSSN() + "\"}";
    }   
}

src/main/java/entities/Manager.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import javax.persistence.Entity;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author matos
 */
@Entity
@XmlRootElement
public class Manager extends StoreUser {

    public Manager() {
        super();
    }

    public Manager(int SSN, String email, String password) {
        super(SSN, email, password);
    }

    @Override
    public String toString() {
        return "{\"ManagerId\":\"" + super.getUserId() + "\", \"Name\":\"" + super.getName() + "\", \"Email\":\"" + super.getEmail() + "\","
                + " \"Address\":\"" + super.getAddress() + "\", \"SSN\":\"" + super.getSSN() + "\"}";
    }
}

src/main/java/entities/Product.java
package entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.xml.bind.annotation.XmlRootElement;
import javax.persistence.ManyToMany;

@Entity
@XmlRootElement
public class Product implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long productId;
    private String name;
    private double price;
    private String description;
    private String imageUrl;
    private String category;
    @ManyToMany(fetch=FetchType.EAGER)
    private List<Provider> listProviders = new ArrayList<>(); 

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    public Long getProductId() {
        return productId;
    }
    public void setDescription(String description){
        this.description = description;
    }

    public String getCategory() {
        return category;
    }
    
    public String getDescription(){
        return description;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public double getPrice() {
        return price;
    }

    public void setPrice(double price) {
        this.price = price;
    }

    public void addProvider(Provider p){
        listProviders.add(p);
    }
    
    public void rmeoveProvider(Provider p){
        listProviders.remove(p);
    }

    public void setCategory(String category) {
        this.category = category;
    }
    public List<Provider> getListProviders() {
        return listProviders;
    }

    public void setListProviders(List<Provider> listProviders) {
        this.listProviders = listProviders;
    }

    @Override
    public String toString() {
        return "{\"productId\":\"" + productId + "\", \"Name\":\"" + name + "\",\"Price\":\"" + price + "\","
                + "\"Description\":\"" + description + "\",\"imageURL\":\"" + imageUrl + "\"" +'}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 59 * hash + Objects.hashCode(this.productId);
        hash = 59 * hash + Objects.hashCode(this.name);
        hash = 59 * hash + (int) (Double.doubleToLongBits(this.price) ^ (Double.doubleToLongBits(this.price) >>> 32));
        hash = 59 * hash + Objects.hashCode(this.description);
        hash = 59 * hash + Objects.hashCode(this.listProviders);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Product other = (Product) obj;
        if (Double.doubleToLongBits(this.price) != Double.doubleToLongBits(other.price)) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.description, other.description)) {
            return false;
        }
        if (!Objects.equals(this.productId, other.productId)) {
            return false;
        }
        if (!Objects.equals(this.listProviders, other.listProviders)) {
            return false;
        }
        return true;
    }
    
    

    

    
    
}

src/main/java/entities/Provider.java
package entities;

import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.xml.bind.annotation.XmlRootElement;

@Entity
@XmlRootElement
public class Provider extends StoreUser{
    @ManyToMany(fetch=FetchType.EAGER)
    private List<Product> prods;
    public Provider(){
        super();
    }
    public Provider(int SSN, String email, String password){
        super(SSN, email, password);
        
        prods = new ArrayList<>();
    }
    public void addProduct(Product p){
        prods.add(p);
    }

    public void removeProduct(Product p){
        prods.remove(p);
    }
    
    @Override
    public String toString() {
        return "{\"ProviderId\":\"" + super.getUserId() + "\", \"Name\":\"" + super.getName() + "\", \"Address\":\"" 
                + super.getAddress() + "\", \"SSN\":\"" + super.getSSN() + "\"}";
    }
}

src/main/java/entities/Sale.java
package entities;

import java.util.AbstractList;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.xml.bind.annotation.XmlRootElement;
import javax.persistence.ManyToOne;

@Entity
@XmlRootElement
public class Sale {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long saleId;
    @ManyToOne
    private Client client;
    @ManyToMany(fetch=FetchType.EAGER)
    private List<Product> listProduct;

    public Sale(Client c){
        listProduct = new ArrayList<>();
        client = c;
    }
    
    public Sale(){
        listProduct = new ArrayList<>();
    }
    public Long getSaleId() {
        return saleId;
    }


    public Client getClient() {
        return client;
    }

    public double getTotalPayedAmount(){
        double amount = 0;
        for(Product prod : listProduct )
            amount += prod.getPrice();
        return amount;
    }
    
    public int getProductAmount(Product p ){
        int amount = 0;
        for(Product prod: listProduct){
            if(prod == p)
                amount++;
        }
        return amount;
    }
    
    public int getTotalproductAmount(){
        return listProduct.size();
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

    public List<Product> getListProduct() {
        return listProduct;
    }

    public void setListProduct(List<Product> listProduct) {
        this.listProduct = listProduct;
    }
    
    public void addProduct(Product p ){
        listProduct.add(p);
    }
    
    public void removeProd(Product p){
        listProduct.remove(p);
    }
    

    @Override
    public String toString() {
        return "{\"SaleId\":\"" + saleId +"\", \"ClientEmail\":\"" + client.getEmail() + "\", \"Products\":" + listProduct + "}";
    }
}

src/main/java/entities/ShoppingCar.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author matos
 */
public class ShoppingCar implements Serializable{
    private List<Product> prods;
    private static final long serialVersionUID = 746972771702940782L;
    public ShoppingCar(){
        prods = new ArrayList<>();
    }
    
    public void addProductAmount(Product p, int amount){
        for(int i = 0; i < amount; i++)
            prods.add(p);
    }
    public void addProduct(Product p){
        prods.add(p);
    }
    
    public void removeProduct(Product p){
        prods.remove(p);
    }
    
    public void clearProducts(){
        prods.clear();
    }
    
    public Product getProduct(Product p){
        return prods.get(prods.indexOf(p));
    }
    public Product getProduct(long proId){
        Product searchProduct = null;
        for(Product p : prods){
            if(p.getProductId() == proId){
                searchProduct = p;
            }
        }
        return searchProduct;
    }
    public List<Product> getProducts(){
        return cloneList(prods);
    }
    
    private List<Product> cloneList(List<Product> list){
        List<Product> clone = new ArrayList<>();
        for(Iterator<Product> it = list.iterator(); it.hasNext(); ){
            clone.add(it.next());
        }
        return clone;
    }
    
    public int getProductAmount(Product p ){
        int amount = 0;
        for(Product prod: prods){
            if(prod == p)
                amount++;
        }
        return amount;
    }
    
    @Override
    public String toString(){
        return prods.toString();
    }
}

src/main/java/entities/StoreUser.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package entities;

import java.io.Serializable;
import java.util.Objects;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.MappedSuperclass;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author matos
 */
@Entity
@Inheritance(strategy=InheritanceType.JOINED)
@MappedSuperclass
@XmlRootElement
public class StoreUser implements Serializable{
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long userId;
    private String name;
    private String email;
    private String password;
    private String address;
    private int SSN;
    private static final long serialVersionUID = 1L;

    public StoreUser() {
    }
    
    public StoreUser(int SSN, String email, String password){
        this.SSN = SSN;
        this.email = email;
        this.password = password;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public void setSSN(int SSN) {
        this.SSN = SSN;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public Long getUserId() {
        return userId;
    }

    public String getEmail() {
        return email;
    }

    public int getSSN() {
        return SSN;
    }
    
    public String getPass(){
        return password;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 37 * hash + Objects.hashCode(this.userId);
        hash = 37 * hash + Objects.hashCode(this.name);
        hash = 37 * hash + Objects.hashCode(this.email);
        hash = 37 * hash + Objects.hashCode(this.password);
        hash = 37 * hash + Objects.hashCode(this.address);
        hash = 37 * hash + this.SSN;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final StoreUser other = (StoreUser) obj;
        if (this.SSN != other.SSN) {
            return false;
        }
        if (!Objects.equals(this.name, other.name)) {
            return false;
        }
        if (!Objects.equals(this.email, other.email)) {
            return false;
        }
        if (!Objects.equals(this.password, other.password)) {
            return false;
        }
        if (!Objects.equals(this.address, other.address)) {
            return false;
        }
        if (!Objects.equals(this.userId, other.userId)) {
            return false;
        }
        return true;
    }
    
    
}

src/main/java/managedBeans/SessionBean.java
package managedBeans;

import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpSession;
 
public class SessionBean {
 
    public static HttpSession getSession() {
        return (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
    }
 
    public static HttpServletRequest getRequest() {
        return (HttpServletRequest) FacesContext.getCurrentInstance()
                .getExternalContext().getRequest();
    }
 
    public static String getUserName() {
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
                .getExternalContext().getSession(false);
        if (session.getAttribute("username") == null)
            return null;
        return session.getAttribute("username").toString();
    }
    
    public static String getUserType(){
        HttpSession session = (HttpSession) FacesContext.getCurrentInstance()
           .getExternalContext().getSession(false);
        String type = session.getAttribute("type").toString();
        if (type == null)
            return null;
        return type;
    }
}

src/main/webapp/manageClients.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html  xmlns="http://www.w3.org/1999/xhtml"
       xmlns:h="http://java.sun.com/jsf/html"
       xmlns:f="http://java.sun.com/jsf/core"
       xmlns:ui="http://java.sun.com/jsf/facelets"
       xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
            <title>General Store</title>
            <link rel="stylesheet" href="resources/css/stylesheet.css"/>
        </h:head>
        <h:body>
            <p:layout fullPage="true" rendered="#{LoginView.userType == 'manager'}">
                <p:layoutUnit position="south" size="auto" closable="false" collapsible="false" >
                    <h4 align="middle">General Store - 2016 | Contactos: 239 255 555</h4>
                </p:layoutUnit>
                <p:layoutUnit position="center">
                    <div id="header">
                        <a href="index.xhtml">
                            <img id="logo" src="resources/imgs/logo.png"/>
                        </a>
                    </div>

                    <h:form id="sticky">
                        <p:menubar>
                            <p:menuitem value="Início" outcome="index" icon="ui-icon-home" />
                            <p:menuitem value="Gerir Stock" outcome="manageStock" icon="ui-icon-wrench" />
                            <p:menuitem value="Gerir Clientes" outcome="manageClients" icon="ui-icon-circle-plus" />
                            <p:menuitem value="Gerir Fornecedores" outcome="manageProviders" icon="ui-icon-clipboard" />
                            <f:facet name="options">
                                <p:outputLabel value="Olá, #{LoginView.getLoggedUser()}  " rendered="#{LoginView.userLoggedIn}" />
                                <p:commandButton value="Login" action="login" rendered="#{!LoginView.userLoggedIn}"/>
                                <p:commandButton value="Logout" action="#{LoginView.logout()}" rendered="#{LoginView.userLoggedIn}"/>
                            </f:facet>
                        </p:menubar>
                    </h:form>
                    <h:form>
                        <p:selectOneMenu id="category" value="#{ProductView.category}" style="width:125px">
                            <f:selectItem itemLabel="Todos" itemValue="Todos" />
                            <f:selectItem itemLabel="Eletrodomésticos" itemValue="Eletrodomésticos" />
                            <f:selectItem itemLabel="Telemóveis e Acessórios" itemValue="Telemóveis e Acessórios" />
                            <f:selectItem itemLabel="Imagem e Som" itemValue="Imagem e Som" />
                            <f:selectItem itemLabel="Brinquedos e Videojogos" itemValue="Brinquedos e Videojogos" />
                            <f:selectItem itemLabel="Desporto e Lazer" itemValue="Desporto e Lazer" />
                            <f:selectItem itemLabel="Moda e Acessórios" itemValue="Moda e Acessórios" />
                            <f:selectItem itemLabel="Saúde e Beleza" itemValue="Saúde e Beleza" />
                            <f:selectItem itemLabel="Auto e Moto" itemValue="Auto e Moto" />
                            <f:selectItem itemLabel="Casa e Decoração" itemValue="Casa e Decoração" />
                            <f:selectItem itemLabel="Escritório e Mobiliário" itemValue="Escritório e Mobiliário" />
                            <f:selectItem itemLabel="Gastronomia e Vinhos" itemValue="Gastronomia e Vinhos" />
                            <f:selectItem itemLabel="Livros" itemValue="Livros" />
                        </p:selectOneMenu>
                        <p:commandButton value="Filtrar" update="prodList"/>
                        <p:commandButton value="Atualizar clientes" update="prodList"/>
                    </h:form>


                    <p:dataTable id="prodList" var="client" value="#{UserView.allClients}" editable="false" style="margin-bottom:20px">
                        <f:facet name="header">
                            Gerir Clientes
                        </f:facet>

                        <p:column headerText="Id">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.userId}" /></f:facet>
                                <f:facet name="input"><p:inputText id="modelInput" value="#{client.userId}" style="width:100%"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Nome">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.name}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.name}" style="width:100%" label="Nome"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Email">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.email}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.email}" style="width:100%" label="Descrição"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Password">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.pass}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.pass}" style="width:100%" label="Descrição"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Endereço">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.address}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.address}" style="width:100%" label="Imagem"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column style="width:200px">
                            <h:form>
                                <p:commandButton value="Eliminar" action="#{UserView.deleteClient(client.userId)}" update="prodList"/>
                            </h:form>
                        </p:column>
                    </p:dataTable>


                    <!--<div style="height: 200px; width: 200px; background-color: gainsboro; align-content: center; padding: 30px; margin-top: 10px; align-items: center">
                        <img src="resources/imgs/cachoFresco.jpg" height="140px"/>
                        <h3>Vinho Cacho Fresco</h3>
                        <p>1.50€</p>
                        <p:button outcome="productDetail" icon="ui-icon ui-icon-search" value="Ver Produto" style="margin:0 auto;"
                                  title="Icon Only">
                        </p:button>

                    </div>-->
                </p:layoutUnit>
            </p:layout>
        </h:body>
    </f:view>
</html>

src/main/webapp/manageProviders.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html  xmlns="http://www.w3.org/1999/xhtml"
       xmlns:h="http://java.sun.com/jsf/html"
       xmlns:f="http://java.sun.com/jsf/core"
       xmlns:ui="http://java.sun.com/jsf/facelets"
       xmlns:p="http://primefaces.org/ui">
    <f:view contentType="text/html">
        <h:head>
            <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
            <title>General Store</title>
            <link rel="stylesheet" href="resources/css/stylesheet.css"/>
        </h:head>
        <h:body>
            <p:layout fullPage="true" rendered="#{LoginView.userType == 'manager'}">
                <p:layoutUnit position="south" size="auto" closable="false" collapsible="false" >
                    <h4 align="middle">General Store - 2016 | Contactos: 239 255 555</h4>
                </p:layoutUnit>
                <p:layoutUnit position="center">
                    <div id="header">
                        <a href="index.xhtml">
                            <img id="logo" src="resources/imgs/logo.png"/>
                        </a>
                    </div>

                    <h:form id="sticky">
                        <p:menubar>
                            <p:menuitem value="Início" outcome="index" icon="ui-icon-home" />
                            <p:menuitem value="Gerir Stock" outcome="manageStock" icon="ui-icon-wrench" />
                            <p:menuitem value="Gerir Clientes" outcome="manageClients" icon="ui-icon-circle-plus" />
                            <p:menuitem value="Gerir Fornecedores" outcome="manageProviders" icon="ui-icon-clipboard" />
                            <f:facet name="options">
                                <p:outputLabel value="Olá, #{LoginView.getLoggedUser()}  " rendered="#{LoginView.userLoggedIn}" />
                                <p:commandButton value="Login" action="login" rendered="#{!LoginView.userLoggedIn}"/>
                                <p:commandButton value="Logout" action="#{LoginView.logout()}" rendered="#{LoginView.userLoggedIn}"/>
                            </f:facet>
                        </p:menubar>
                    </h:form>
                    <h:form>
                        <p:selectOneMenu id="category" value="#{ProductView.category}" style="width:125px">
                            <f:selectItem itemLabel="Todos" itemValue="Todos" />
                            <f:selectItem itemLabel="Eletrodomésticos" itemValue="Eletrodomésticos" />
                            <f:selectItem itemLabel="Telemóveis e Acessórios" itemValue="Telemóveis e Acessórios" />
                            <f:selectItem itemLabel="Imagem e Som" itemValue="Imagem e Som" />
                            <f:selectItem itemLabel="Brinquedos e Videojogos" itemValue="Brinquedos e Videojogos" />
                            <f:selectItem itemLabel="Desporto e Lazer" itemValue="Desporto e Lazer" />
                            <f:selectItem itemLabel="Moda e Acessórios" itemValue="Moda e Acessórios" />
                            <f:selectItem itemLabel="Saúde e Beleza" itemValue="Saúde e Beleza" />
                            <f:selectItem itemLabel="Auto e Moto" itemValue="Auto e Moto" />
                            <f:selectItem itemLabel="Casa e Decoração" itemValue="Casa e Decoração" />
                            <f:selectItem itemLabel="Escritório e Mobiliário" itemValue="Escritório e Mobiliário" />
                            <f:selectItem itemLabel="Gastronomia e Vinhos" itemValue="Gastronomia e Vinhos" />
                            <f:selectItem itemLabel="Livros" itemValue="Livros" />
                        </p:selectOneMenu>
                        <p:commandButton value="Filtrar" update="prodList"/>
                        <p:commandButton value="Atualizar fornecedores" update="prodList"/>
                    </h:form>


                    <p:dataTable id="prodList" var="client" value="#{UserView.allProviders}" editable="false" style="margin-bottom:20px">
                        <f:facet name="header">
                            Gerir Clientes
                        </f:facet>

                        <p:column headerText="Id">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.userId}" /></f:facet>
                                <f:facet name="input"><p:inputText id="modelInput" value="#{client.userId}" style="width:100%"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Nome">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.name}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.name}" style="width:100%" label="Nome"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Email">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.email}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.email}" style="width:100%" label="Descrição"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Password">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.pass}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.pass}" style="width:100%" label="Descrição"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column headerText="Endereço">
                            <p:cellEditor>
                                <f:facet name="output"><h:outputText value="#{client.address}" /></f:facet>
                                <f:facet name="input"><p:inputText value="#{client.address}" style="width:100%" label="Imagem"/></f:facet>
                            </p:cellEditor>
                        </p:column>

                        <p:column style="width:200px">
                            <h:form>
                                <p:commandButton value="Eliminar" action="#{UserView.deleteProvider(client.userId)}" update="prodList"/>
                            </h:form>
                        </p:column>
                    </p:dataTable>


                    <!--<div style="height: 200px; width: 200px; background-color: gainsboro; align-content: center; padding: 30px; margin-top: 10px; align-items: center">
                        <img src="resources/imgs/cachoFresco.jpg" height="140px"/>
                        <h3>Vinho Cacho Fresco</h3>
                        <p>1.50€</p>
                        <p:button outcome="productDetail" icon="ui-icon ui-icon-search" value="Ver Produto" style="margin:0 auto;"
                                  title="Icon Only">
                        </p:button>

                    </div>-->
                </p:layoutUnit>
            </p:layout>
        </h:body>
    </f:view>
</html>